output "pet-name" {
  value       = random_pet.mypet
  description = "Record name generated by random_pet.mypet"
}

output "new-name" {
  value       = data.local_file.dog
  description = "Record name generated by data.local_file.dog"
}

